In [3]:
import torch
import numpy as np



In [4]:
ts = torch.tensor([[1,2],[3,4]])
print(ts)
print(ts.shape)
print(ts.dtype)
print(ts.device)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
cpu


In [5]:
ts2 = torch.tensor([[1,2]])
print(torch.cat([ts,ts2],dim=0))
print(ts.matmul(ts2.T))
print(ts.mul(ts2))
print(ts2.T)

tensor([[1, 2],
        [3, 4],
        [1, 2]])
tensor([[ 5],
        [11]])
tensor([[1, 4],
        [3, 8]])
tensor([[1],
        [2]])


In [6]:
print(ts2.matmul(ts.matmul(ts2.T)).item())
print(ts.add(10))



27
tensor([[11, 12],
        [13, 14]])


In [7]:
x = torch.tensor([1], requires_grad=True, dtype=torch.float)
y = torch.tensor([2], requires_grad=True, dtype=torch.float)

z = x**2 + y**3
z.backward()
print(x.grad)
print(y.grad)

tensor([2.])
tensor([12.])


In [8]:
import math
from numpy import ndarray

#FUNCTIONS

#OPERATORS

def annihilation(dimension: int) -> ndarray:
    """
    Returns a dense matrix of size dimension x dimension representing the annihilation
    operator in number basis.
    """
    offdiag_elements = np.sqrt(range(1, dimension))
    return np.diagflat(offdiag_elements, 1)

def creation(dimension: int) -> ndarray:
    """
    Returns a dense matrix of size dimension x dimension representing the creation
    operator in number basis.
    """
    return annihilation(dimension).T




In [94]:
#MORE NOISE RELATED FUNCTIONS

#SOME GLOBAL PARAMETERS
R_k = sp.constants.h / (sp.constants.e**2.0)
R_0 = 50
T = 0.015
M = 400
Delta = 3.4e-4
x_qp = 3e-6

#T1 CAPACITIVE
import scipy as sp
import scipy.constants

def q_cap_fun(omega) -> torch.Tensor:
    return (
        1e6
        * (2 * np.pi * 6e9 / torch.abs(omega)) ** 0.7
    )

def calc_therm_ratio(
    omega: float, T: float
) -> torch.Tensor:
    return (sp.constants.hbar * omega) / (sp.constants.k * T)

def spectral_density_cap(omega,EJ,EC,EL,flux):
    
    therm_ratio = calc_therm_ratio(omega, T)
    s = (
        2
        * 8
        * EC
        / q_cap_fun(omega)
        * (1 / torch.tanh(0.5 * torch.abs(therm_ratio)))
        / (1 + torch.exp(-therm_ratio))
    )
    s *= (
        2 * np.pi
    )  # We assume that system energies are given in units of frequency
    return s



In [53]:
#MORE NOISE RELATED FUNCTIONS

#T1 CHARGE IMPEDANCE

def spectral_density_ci(omega,EJ,EC,EL,flux):
    # Note, our definition of Q_c is different from Zhang et al (2020) by a
    # factor of 2

    Q_c = R_k / (8 * np.pi * complex(R_0).real)
    therm_ratio = calc_therm_ratio(omega, T)
    s = (
        2
        * ( omega / 1e9 ) #annoying unit stuff - gotta convert back to GHz
        / Q_c
        * (1 / torch.tanh(0.5 * therm_ratio))
        / (1 + torch.exp(-therm_ratio))
    )
    return s


def spectral_density_fbl(omega,EJ,EC,EL,flux):
    """
    Our definitions assume that the noise_op is dH/dflux.
    """

    therm_ratio = calc_therm_ratio(omega, T)

    s = (
        2
        * (2 * np.pi) ** 2
        * M**2
        * ( omega / 1e9 ) #annoying unit stuff - gotta convert back to GHz
        * sp.constants.hbar
        / complex(R_0).real
        * (1 / torch.tanh(0.5 * therm_ratio))
        / (1 + torch.exp(-therm_ratio))
    )
    # We assume that system energies are given in units of frequency and that
    # the noise operator to be used with this `spectral_density` is dH/dflux.
    # Hence we have to convert  2 powers of frequency to standard units
    s *= 1e9 ** 2.0
    return s



In [92]:
def q_ind_fun(omega):

    therm_ratio = abs(calc_therm_ratio(omega, T))
    therm_ratio_500MHz = calc_therm_ratio(
        torch.tensor(2 * np.pi * 500e6), T
    )
    
    return (
        500e6
        * (
            torch.special.scaled_modified_bessel_k0(1 / 2 * therm_ratio_500MHz)
            * torch.sinh(1 / 2 * therm_ratio_500MHz)
            / torch.exp(1 / 2 * therm_ratio_500MHz)
        )
        / (
            torch.special.scaled_modified_bessel_k0(1 / 2 * therm_ratio)
            * torch.sinh(1 / 2 * therm_ratio)
            / torch.exp(1 / 2 * therm_ratio)
        )
    )

def spectral_density_ind(omega,EJ,EC,EL,flux):

    therm_ratio = calc_therm_ratio(omega,T)
    s = (
        2
        * EL
        / q_ind_fun(omega)
        * (1 / torch.tanh(0.5 * torch.abs(therm_ratio)))
        / (1 + torch.exp(-therm_ratio))
    )
    s *= (
        2 * np.pi
    )  # We assume that system energies are given in units of frequency
    return s

In [156]:
def y_qp_fun(omega,EJ,EC,EL,flux):
    """
    Based on Eq. S23 in the appendix of Smith et al (2020).
    """
    # Note that y_qp_fun is always symmetric in omega, i.e. In Smith et al 2020,
    # we essentially have something proportional to sinh(omega)/omega
    omega = torch.abs(omega)
    Delta_in_Hz = Delta * sp.constants.e / sp.constants.h

    omega_in_Hz = omega / (2 * np.pi) 
    EJ_in_Hz = EJ * 1e9 # GHz to Hz

    therm_ratio = calc_therm_ratio(omega, T)
    Delta_over_T = calc_therm_ratio(
        2 * np.pi * Delta_in_Hz, T
    )

    re_y_qp = (
        np.sqrt(2 / np.pi)
        * (8 / R_k)
        * (EJ_in_Hz / Delta_in_Hz)
        * (2 * Delta_in_Hz / omega_in_Hz) ** (3 / 2)
        * x_qp
        * torch.sqrt(1 / 2 * therm_ratio)
        * torch.special.scaled_modified_bessel_k0(1 / 2 * torch.abs(therm_ratio))
        * torch.sinh(1 / 2 * therm_ratio)
        / torch.exp(1 / 2 * torch.abs(therm_ratio))
    )

    return re_y_qp

def spectral_density_qt(omega,EJ,EC,EL,flux):
    """Based on Eq. 19 in Smith et al (2020)."""
    therm_ratio = calc_therm_ratio(omega, T)

    return (
        2
        * omega / 1e9
        * complex(y_qp_fun(omega,EJ,EC,EL,flux)).real
        * (1 / torch.tanh(0.5 * therm_ratio))
        / (1 + torch.exp(-therm_ratio))
    )

In [119]:
#GENERAL T1 function
from numpy import ndarray 
from typing import Any, Callable, Dict, List, Optional, Tuple, Union, cast

def t1(
        noise_op: torch.Tensor,
        spectral_density: Callable,
        eigvals: torch.Tensor,
        eigvecs: torch.Tensor,
        EJ: torch.Tensor,
        EC: torch.Tensor,
        EL: torch.Tensor,
        flux: torch.Tensor,
        i: int = 1,
        j: int = 0
    ):

        # We assume that the energies in `evals` are given in the units of frequency
        # and *not* angular frequency. The function `spectral_density` is assumed to
        # take as a parameter an angular frequency, hence we have to convert.


        ground = eigvecs[:,j]
        excited = eigvecs[:,i]
        ground_E = eigvals[j]
        excited_E = eigvals[i]

        omega = 2 * np.pi * (excited_E - ground_E) * 1e9

        s = (
            spectral_density(omega,EJ,EC,EL,flux) + spectral_density(-omega,EJ,EC,EL,flux)
        )
        
        rate = torch.matmul(noise_op,ground.unsqueeze(0).T)
        rate = torch.matmul(excited.unsqueeze(0).conj(),rate)
        rate = torch.abs(rate) **2 * s
        #print(torch.abs(torch.matmul(excited.unsqueeze(0).conj(),torch.matmul(noise_op,ground.unsqueeze(0).T))))

        return rate

In [218]:
def t1_effective (
    EJ: torch.Tensor,
    EC: torch.Tensor,
    EL: torch.Tensor,
    flux: torch.Tensor,
    dim: float,
):
    
    # PART 1 - GET HAMILTONIAN
    plasma_energy = math.sqrt(8.0*EL*EC)
    diag_elements = [(i + 0.5) for i in range(dim)]
    lc_osc = torch.tensor(np.diag(diag_elements),dtype=torch.double)
    lc_osc = lc_osc * plasma_energy

    phi_osc = (8.0 * EC / EL) ** 0.25
    phi = (
            (torch.tensor(creation(dim),dtype=torch.double) + torch.tensor(annihilation(dim),dtype=torch.double))
            * phi_osc/ math.sqrt(2)
        )

    argument = phi + 2 * np.pi * flux * torch.tensor(np.eye(dim),dtype=torch.double)

    cos_phi = (torch.linalg.matrix_exp(argument*1j)+torch.linalg.matrix_exp(argument*-1j))/2
    sin_phi = (torch.linalg.matrix_exp(argument*1j)-torch.linalg.matrix_exp(argument*-1j))/2j

    n_op = (
                1j
                * (torch.tensor(creation(dim),dtype=torch.double) - torch.tensor(annihilation(dim),dtype=torch.double))
                / (phi_osc * math.sqrt(2))
            )

    d_ham_d_flux = -2 * np.pi * EJ * sin_phi

    H = lc_osc - EJ*cos_phi
    #H = torch.triu(H, diagonal=1).T + torch.triu(H)
    #H.to(torch.double)

    #PART 2 - Get eigenvalues

    eigvals,eigvecs = torch.linalg.eigh(H,UPLO='U')

    # PART 3 - Find rate

    t1_rate = torch.zeros([1,1],dtype=torch.double)

    #3.1 t1_capacitive

    t1_rate += t1(n_op, spectral_density_cap, eigvals, eigvecs, EJ, EC, EL, flux)

    #3.2 t1_charge_impedance

    #t1_rate += t1(n_op, spectral_density_ci, eigvals, eigvecs, EJ, EC, EL, flux)

    #3.3 t1_flux_bias_line

    t1_rate += t1(d_ham_d_flux, spectral_density_fbl, eigvals, eigvecs, EJ, EC, EL, flux)

    #3.4 t1_inductive

    t1_rate += t1(phi.to(torch.cdouble), spectral_density_ind, eigvals, eigvecs, EJ, EC, EL, flux)

    #3.5 t1_quasiparticle_tunneling - a little dubious

    qt_argument = argument/2
    qt_noise = (torch.linalg.matrix_exp(qt_argument*1j)-torch.linalg.matrix_exp(qt_argument*-1j))/2j

    #t1_rate += t1(qt_noise.to(torch.cdouble), spectral_density_qt, eigvals, eigvecs, EJ, EC, EL, flux)

    # PART 4 - Get time

    T1 = 1/t1_rate

    return T1

In [220]:
#TENSORS

# INPUT

EJ = torch.tensor([8.9], requires_grad=True, dtype=torch.double)
EC = torch.tensor([2.5], requires_grad=True, dtype=torch.double)
EL = torch.tensor([0.5], requires_grad=True, dtype=torch.double)
flux = torch.tensor([0.5], requires_grad=True, dtype=torch.double)

# PARAMETERS

dim = 110

convergence_ratio = 1e-4
learn_rate = 1e2

# BOUNDS

EJ_bounds = [1e-3, 100]
EC_bounds = [1e-3, 100]
EL_bounds = [1e-3, 100]
flux_bounds = [0,1]

# GRADIENT DESCENT

for i in range(0,1000):

    T1 = t1_effective(EJ,EC,EL,flux,dim)
    T1_rate = 1/T1
    T1_rate.backward()

    print("CYCLE: ",i)
    #print("T1 = ",T1)
    print("T1_rate = ",T1_rate)
    print("EJ,EC,EL,flux = ",EJ.item(),EC.item(),EL.item(),flux.item())
    print("change EJ,EC,EL,flux = ",EJ.grad.item()*learn_rate,EC.grad.item()*learn_rate,EL.grad.item()*learn_rate,flux.grad.item()*learn_rate)
    
    if EJ.data - EJ.grad.data*learn_rate > EJ_bounds[0] and EJ.data - EJ.grad.data*learn_rate < EJ_bounds[1]:
        EJ.data = EJ.data - EJ.grad.data*learn_rate
    
    if EC.data - EC.grad.data*learn_rate > EC_bounds[0] and EC.data - EC.grad.data*learn_rate < EC_bounds[1]:
        EC.data = EC.data - EC.grad.data*learn_rate
    
    if EL.data - EL.grad.data*learn_rate > EL_bounds[0] and EL.data - EL.grad.data*learn_rate < EL_bounds[1]:
        EL.data = EL.data - EL.grad.data*learn_rate

    if flux.data - flux.grad.data*learn_rate > flux_bounds[0] and flux.data - flux.grad.data*learn_rate < flux_bounds[1]:
        flux.data = flux.data - flux.grad.data*learn_rate

    EJ.grad.data.zero_()
    EC.grad.data.zero_()
    EL.grad.data.zero_()
    flux.grad.data.zero_()


CYCLE:  0
T1_rate =  tensor([[3.8419e-07]], dtype=torch.float64, grad_fn=<MulBackward0>)
EJ,EC,EL,flux =  8.9 2.5 0.5 0.5
change EJ,EC,EL,flux =  -5.682523272718386e-06 1.1616382006283438e-05 1.69285801612775e-05 -8.775720512167862e-17
CYCLE:  1
T1_rate =  tensor([[3.8418e-07]], dtype=torch.float64, grad_fn=<MulBackward0>)
EJ,EC,EL,flux =  8.900005682523274 2.499988383617994 0.4999830714198387 0.5000000000000001
change EJ,EC,EL,flux =  -5.6821595229570065e-06 1.1615872025163364e-05 1.6929945769123438e-05 -9.615460566615443e-17
CYCLE:  2
T1_rate =  tensor([[3.8417e-07]], dtype=torch.float64, grad_fn=<MulBackward0>)
EJ,EC,EL,flux =  8.900011364682797 2.4999767677459688 0.4999661414740696 0.5000000000000002
change EJ,EC,EL,flux =  -5.681795785865119e-06 1.1615362050487695e-05 1.6931311371447334e-05 -1.2346673153786985e-16
CYCLE:  3
T1_rate =  tensor([[3.8416e-07]], dtype=torch.float64, grad_fn=<MulBackward0>)
EJ,EC,EL,flux =  8.900017046478583 2.4999651523839184 0.49994921016269817 0.5000

In [174]:
import scqubits as scq
import scqubits.core.noise as noise
import scqubits.core.units as units
import numpy as np
import torch
from numpy import ndarray
import math


fluxonium = scq.Fluxonium(EJ = 8.9,
                               EC = 2.5,
                               EL = 0.5,
                               flux = 0.5,
                               cutoff = 110)

fluxonium.t1_effective(get_rate=False)

2602877.231907907